spring:
  datasource:
    username: sa
    url: jdbc:h2:mem:testdb
    password: ''
  h2:
    console:
      enabled: true
      path: /h2-console
  application:
    name: hr-worker
server:
  port: 8001