spring:
  application:
    name: hr-config-server
  cloud:
    config:
      server:
        encrypt:
          enabled: false
        git:
          default-label: main
          uri: https://github.com/Jose-Robert/microservice-repo/
          searchPaths: ms-course-configs
server:
  port: 8888

